services:
  lastfm-now-playing:
    image: ghcr.io/alexraskin/lastfm-now-playing:${GIT_COMMIT_HASH:-latest}
    networks:
      - traefik-public
    secrets:
      - lastfm-api-key
    environment:
      - LASTFM_API_KEY=/run/secrets/lastfm-api-key
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=traefik-public"

        - "traefik.http.routers.lastfm-now-playing-https.rule=Host(`lastfm.alexraskin.com`) || Host(`www.lastfm.alexraskin.com`) || Host(`lastfm.twizy.sh`) || Host(`www.lastfm.twizy.sh`)"
        - "traefik.http.routers.lastfm-now-playing-https.entrypoints=https"
        - "traefik.http.routers.lastfm-now-playing-https.tls=true"
        - "traefik.http.routers.lastfm-now-playing-https.tls.certresolver=le"

        - "traefik.http.routers.lastfm-now-playing-https.middlewares=redirect-lastfm-alexraskin,redirect-lastfm-twizy"

        - "traefik.http.middlewares.redirect-lastfm-alexraskin.redirectregex.regex=^https?://lastfm\\.alexraskin\\.com(.*)"
        - "traefik.http.middlewares.redirect-lastfm-alexraskin.redirectregex.replacement=https://www.lastfm.alexraskin.com$${1}"
        - "traefik.http.middlewares.redirect-lastfm-alexraskin.redirectregex.permanent=true"

        - "traefik.http.middlewares.redirect-lastfm-twizy.redirectregex.regex=^https?://lastfm\\.twizy\\.sh(.*)"
        - "traefik.http.middlewares.redirect-lastfm-twizy.redirectregex.replacement=https://www.lastfm.twizy.sh$${1}"
        - "traefik.http.middlewares.redirect-lastfm-twizy.redirectregex.permanent=true"

        - "traefik.http.services.lastfm-now-playing-https.loadbalancer.server.port=3000"

      update_config:
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  traefik-public:
    external: true

secrets:
  LASTFM_API_KEY:
    external: true
